#!/usr/bin/env bash
# Submit CS701 Project program as a job to ada

# Set SLURM options (you should not need to change these)
#SBATCH --job-name=Undercover-Salamander        # Job name
#SBATCH --output=salamander-%j.out              # Name for output log file (%j is job ID)
#SBATCH --cpus-per-task=36                      # Request the entire node
#SBATCH --partition=long                        # Partition (queue) 
#SBATCH --time=4-00:00:00                       # Time limit hrs:min:sec
#SBATCH --exclude=node[018-019]                 # Only use "original" nodes with 36 cores

# DONT MODIFY THE SLURM OPTIONS ABOVE THIS LINE

# Print SLURM envirionment variables
echo "# Job Info ----------------------------"
echo "Job ID: ${SLURM_JOB_ID}"
echo "Node: ${SLURMD_NODENAME}"
echo "Starting: "`date +"%D %T"`

echo -e "\n# Run Results -------------------------"
# in a new environment, use "conda create -n {name} python={version}" in this project, version=3.10
# use "conda activate 701" in terminal before sbatch
python3 ./src/python/test.py

echo "Ending: "`date +"%D %T"`

# For reference, dump info about the processor
echo -e "\n# CPU Info ----------------------------"
lscpu